### ISSUE TITLE
Possible missing license?

### ISSUE THREAD

**Issue by Splitwirez** [jmanc3/winbar#1]
Just came across this repo recently. Looks quite impressive so far. I happened to show it to a friend, who keenly pointed out that there...doesn't appear to be any license attached? I'm not sure if this was intentional or not, but figured I'd mention it, just in case it was an oversight after all.

~~...if it were me, I'd probably go for a permissive license such as MIT, but hey, that's just my two cents.~~

**Comment by thegamerhat** [comment]
It would be good if the project gets a license soon.

**Comment by a1300** [comment]
@jmanc3 tagging you for visibility
great repo 👍

**Comment by jmanc3** [comment]
I ended up going with GPLv3. At some point in the future, I might go with something less strict like MIT.
