### ISSUE TITLE
Hover highlight stays stuck

### ISSUE THREAD

**Issue by pushqrdx** [jmanc3/winbar#14]
So now that the preview getting stuck is fixed, the icon highlight itself is stuck. you can reproduce this by hovering an icon go up to the window preview then leave the area, the icon will stay highlighted

**Comment by jmanc3** [comment]
This is the one where it renders itself correctly after a second or so right?

**Comment by jmanc3** [comment]
If it is, then it's fixed in 82422c7.

**Comment by pushqrdx** [comment]
with 82422c7 it doesn't get stuck anymore but still it keeps being highlighted for some timeout first

**Comment by jmanc3** [comment]
I see what you mean. Fixed in 726a7a5.

**Comment by pushqrdx** [comment]
@jmanc3 not sure if the delay is fixed i still see some delay before the highlight goes away

**Comment by jmanc3** [comment]
@pushqrdx do you mean that the icon stays "hovered" while the preview window is open? _That_ is intentional. The preview not closing immediately is also intentional.
