### ISSUE TITLE
Parsing error:  /root/.config/winbar/winbar.cfg Line: 681 Error: syntax error

### ISSUE THREAD

**Issue by pushqrdx** [jmanc3/winbar#20]
I am still getting this with a fresh master + latest winbar.zip, it's because of the trailing comma at line 678

**Comment by jmanc3** [comment]
Will remove the trailing comma in the next version of "winbar.zip" along with adding the theme variables for configuring notification colors and the action center colors.

**Comment by jmanc3** [comment]
@pushqrdxdo do you still get parsing errors on the latest commit?

**Comment by pushqrdx** [comment]
@jmanc3 nope just tried works fine for me, gonna close this
