### ISSUE TITLE
START Menu: Some applications don't appear 

### ISSUE THREAD

**Issue by themagicalcats** [jmanc3/winbar#23]
Distro: Arch Linux

So most of the applications that you would find in like a menu like Rofi don't appear in the Start Menu using Winbar.

**Comment by jmanc3** [comment]
I haven't used Rofi much so I don't know what it shows but this is what we do:

The start menu only shows "[.desktop](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html)" files.
The tab "Apps" in the search menu also only shows those desktop files.
The tab "Scripts" in the search menu shows the results dmenu would show.

Is there something you feel should be different? Or maybe we should add another tab to the search menu that'll show Rofi like results? And if so, how do those results differ?

**Comment by themagicalcats** [comment]
Well for a start, results that normally show up in rofi do not show up in winbar start menu, for example lets say the XFCE Whisker Menu (hopefully you used that before), it shows more applications that are installed than winbar does.

"Is there something you feel should be different?"
Well in my opinion maybe make it so people can see more results, that'd be amazing. :D

"Or maybe we should add another tab to the search menu that'll show Rofi like results? And if so, how do those results differ?"
That might not be needed because that's already being implemented in the start menu just with less results (the results need a little work), also the difference between applications shown is pretty large, I noticed big chunk of programs missing (not entirely sure why).

_Hope I got what you meant._

**Comment by parkerlreed** [comment]
One thing I noticed. It doesn't show user desktop files. Only /usr/share/applications seems to be scanned.

~/.local/share/applications is ignored.

**Comment by parkerlreed** [comment]
It's weird because this is after this commit https://github.com/jmanc3/winbar/commit/ec804fe3fe5d22209ebcf1dc6f86395da3bc6364

**Comment by parkerlreed** [comment]
```
    local_desktop_files += "/.local/share/applications/";
```

Is this missing the home folder reference? Seems like it's trying .local from root /

**Comment by parkerlreed** [comment]
Oh sorry. *Wasnt* on the latest commit. It is working now. Thanks.
