### ISSUE TITLE
Error message when attempting to access settings

### ISSUE THREAD

**Issue by bornagainpenguin** [jmanc3/winbar#25]
Running Ubuntu-Mate 20.04.2 LTS on a Lenovo Thinkpad x250.

Building the deb installer went fine and the application ran when run from the terminal.  Trying to access settings however seemed to cause the application to relaunch with the following text in the terminal:

dbus[51534]: Attempted to unregister path (path[0] = org path[1] = freedesktop) which isn't registered

Thank you for the interesting project!

**Comment by jmanc3** [comment]
@bornagainpenguin
That's actually the intended behavior right now. It does a full restart of the taskbar which I mainly use for quickly checking different config settings. Eventually an actual GUI settings page is planned though which will make it so people don't have to manually edit config files. As for the dbus error, it's better if didn't happen of course, but it's not a critical error. I'll fix it eventually.
