### ISSUE TITLE
Feature suggestion: Ability to change the clock fonts sizes

### ISSUE THREAD

**Issue by bornagainpenguin** [jmanc3/winbar#26]
I used to be a huge fan of a small app called Lclock, which was intended to make a Longhorn type clock\calendar panel for users of Windows XP.  I was thinking it might be of interest to you as a possible feature enhancement.  There is a somewhat good image of how it looked here:

https://www.deviantart.com/razcalinside/art/RefreshCL-LClock-Skin-27592756

Unfortunately that image there doesn't quite do it justice.  I had the hour cranked up as large as the taskbar could take without breaking it and the minutes smaller with the AM/PM resting underneath the minutes.  The settings in that image aren't nearly large enough.

Just wanted to suggest it as a possible item of interest.  Thanks again for the interesting project!

**Comment by jmanc3** [comment]
As of e5b8e52, You can set the date style to "Windows Vista" and crank the font size up. It's not exactly stacked like Lclock, but similar enough.
