### ISSUE TITLE
packages required for compiling on fedora 

### ISSUE THREAD

**Issue by kleinermob** [jmanc3/winbar#27]
git cmake g++ cairo-devel pango-devel librsvg2-devel xcb-util-devel pulseaudio-libs-devel xcb-util-wm-devel libxkbcommon-x11-devel libconfig-devel xcb-util-cursor-devel dbus-devel xcb-util-keysyms-devel

**Comment by jmanc3** [comment]
@kleinermob 
Thanks! Just tested it out on my virtual machine and it worked. I'll add it to the README.
