### ISSUE TITLE
Application menu does not work properly with two monitors

### ISSUE THREAD

**Issue by Greenlandicsmiley** [jmanc3/winbar#28]
I have two monitors: 1080p on the left and 1440p on the right.

When I have the monitor layout like this (see image below):
![screenshot1](https://user-images.githubusercontent.com/67438283/126101668-f6aa5f0c-9c81-489a-b139-dd4403baa17e.png)

Then the application menu appears on the left monitor and in the wrong position:
![screenshot2](https://user-images.githubusercontent.com/67438283/126102340-04096854-b9c6-4980-8e5a-20faa308645f.png)

But when the left monitor is on the bottom, then Winbar appears on the left monitor and the application menu appears properly:
![screenshot3](https://user-images.githubusercontent.com/67438283/126102690-d906c69f-4bf4-4a51-b672-417a2d3bc806.png)

I tried this first with Openbox, but it produces the same thing when the left monitor is at the top.
Some packages installed on Arch Linux:
xorg-server, xorg-xinit, xorg-xkbcomp, xorg-xrandr, amdgpu driver, linux-zen, as well as the ones listed before installing Winbar

Could this be due to missing configuration on my part?

**Comment by jmanc3** [comment]
@Greenlandicsmiley Nothing is wrong on your part, we just aren't properly placing that menu correctly. Do the other menus show on the correct screen (volume and calendar menus)?

**Comment by Greenlandicsmiley** [comment]
The other menus also behave weirdly when the left monitor is on the top.

Network (also applies to other right side menus):
![network1](https://user-images.githubusercontent.com/67438283/126272716-277fd0cf-1102-44f9-8a9c-a0d656f8389b.png)
![network2](https://user-images.githubusercontent.com/67438283/126272740-6ba28b38-ca44-4368-b267-3e8bad7e41bd.png)


The little icon with an upside down V:
![vicon1](https://user-images.githubusercontent.com/67438283/126274386-e504da5c-1c30-4d41-9e00-307ba7d6f4cb.png)
![vicon2](https://user-images.githubusercontent.com/67438283/126274393-2c6146a6-6aea-49cb-ae76-5029c9d69313.png)

The search menu also has the same problem as the application menu. Where it appears on the left regardless of where it was launched.

**Comment by jmanc3** [comment]
@Greenlandicsmiley Latest commit, f3da5ac72c939878f0f2017aa356f909c36a0da7, shouldn't have this problem anymore. Let me know if it does.

**Comment by Greenlandicsmiley** [comment]
I can confirm it now works properly. Thank you!

I'm not sure if I have to open another issue for this. When the left monitor is on the bottom and I launch Winbar, then it appears on the left and the right monitor does not have it, and blocks programs from using the bottom part of the screen. It can be seen on the first and 3rd screenshots of my last comment.

**Comment by Greenlandicsmiley** [comment]
I'm closing this since the issue on my last comment is a different issue.
