### ISSUE TITLE
Winbar not positioned correctly with a secondary monitor on the left side (kde)

### ISSUE THREAD

**Issue by tam1m** [jmanc3/winbar#31]
As the title says, winbar is not positioning itself correctly with a dual monitor setup, where the secondary monitor is on the left side.
Changing any setting in the display setup, fixes it temporarily until its restarted.
With the second display on the right side, it works perfectly fine. 

Here is a short screenrecording demonstrating the issue
https://user-images.githubusercontent.com/472185/146634563-b1d8202b-b720-4f02-bf9c-d143e881cb23.mp4

System Info:
winbar https://github.com/jmanc3/winbar/commit/74f153ebff21d66653ee517940bf37f1f5d622a3
Archlinux with KDE
Kernel 5.15.8-zen1-1-zen
NVIDIA GeForce GTX 970 (495.46)
Resolution: 1920x1080 @ 119.98Hz, 1680x1050 @ 59.95Hz

**Comment by jmanc3** [comment]
Should be fixed on latest commit 408bbba, let me know!

**Comment by tam1m** [comment]
Working perfectly now!
