### ISSUE TITLE
Power options not implemented

### ISSUE THREAD

**Issue by prateekmedia** [jmanc3/winbar#35]
https://user-images.githubusercontent.com/41370460/153248231-5a0efc18-a162-4af2-b986-154d252a6373.mp4

**Comment by jmanc3** [comment]
This is on purpose for now. "Power" shuts down Winbar and "Settings" restarts it. Haven't gotten around to implementing the sub menu's yet.

**Comment by jmanc3** [comment]
The power menu has been implemented and works currently on KDE. (Gnome will come later.)
