### ISSUE TITLE
Scrolling sound doesn't changes the volume of current sink

### ISSUE THREAD

**Issue by prateekmedia** [jmanc3/winbar#39]
When I have two devices connected, let's say
- TV (Default) (At the top of devices)
- Bluetooth Headset (Active) (At the second place)

and then when I scroll the sound icon it changes the sound of Default sink(TV) but not the active one(Bluetooth headset).

**Comment by jmanc3** [comment]
@prateekmedia Are you running PulseAudio/Pipewire or Alsa?

**Comment by jmanc3** [comment]
Actually I plugged in a second monitor and see what you mean. Problem should be fixed in: [dfbbbcc](https://github.com/jmanc3/winbar/commit/dfbbbcce62a8758d2c9c24cf8290196248d81078)

**Comment by prateekmedia** [comment]
@jmanc3 Thank you for this!
