### ISSUE TITLE
Super + 1, Super + 2 to switch windows or open from the pinned ones

### ISSUE THREAD

**Issue by prateekmedia** [jmanc3/winbar#42]
Windows and many linux de's have this feature of Super + n => Open the nth app pinned in the task list or switch to it if its already opened.

It would be good if this also has it as this already has super to launch start menu.

**Comment by jmanc3** [comment]
I added this feature in [1099a4a](https://github.com/jmanc3/winbar/commit/1099a4a7c4a594ee4776aada8f341482b2020c13), but as of right now, it just always launches a new window. What is the behavior supposed to be if there is already a window open? (If there is only one window, I imagine it just focuses that one. But what if there are multiple recently opened windows? Does it select the most recently focused one?)
