### ISSUE TITLE
Icon cache generation crashes with directory without permissions

### ISSUE THREAD

**Issue by D3SOX** [jmanc3/winbar#43]
I'm at cf17aa78b079e4d4767d05f834ecf3be5319a789

I haven't looked at the code, but I guess you are doing some kind of recursive directory listing, and it crashes once it goes into a folder without permissions.
```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: status: Permission denied [/usr/share/kwin/shaders/1.40/1.40]
[1]    457259 IOT instruction (core dumped)  winbar
```

**Comment by jmanc3** [comment]
@D3SOX it should skip folders it doesn't have permissions to in the latest commit: [d6d0d15](https://github.com/jmanc3/winbar/commit/d6d0d1529df7614f23172335745b26ee4cb4dd42).
Let me know if this fixes your problem.

**Comment by D3SOX** [comment]
That fixed it!
