### ISSUE TITLE
Don't hardcode thunar

### ISSUE THREAD

**Issue by D3SOX** [jmanc3/winbar#44]
When I try to open a folder via the start menu, I get this terminal output
```
sh: 1: thunar: not found
```

I guess you can just `xdg-open` instead of `thunar` to fix it

**Comment by jmanc3** [comment]
Let me know if [657dcc5](https://github.com/jmanc3/winbar/commit/657dcc59d766923726f4c4ca529246c399db1c4d) fixes that

**Comment by D3SOX** [comment]
Correctly opens Dolphin for me now
