### ISSUE TITLE
Doubles in size off the screen and becomes unusable with xfwm4

### ISSUE THREAD

**Issue by Faithy3** [jmanc3/winbar#49]
xfwm4 4.16.1-3.1, using the winbar-git AUR package, r217.gd1f66c8-1, on Arch Linux with linux-lts 5.15.24-2.1 (though I have seen similar behavior on another device with linux-zen a few months ago)
When opening it in a normal Xfce session, immediately becomes twice the intended size, going off the screen.
When opening with startx `winbar & exec xfwm4`, initially shows fine, but no applications will launch, and attempting to open settings makes it double again. When in this state, start and search menus do not appear.
![image](https://user-images.githubusercontent.com/29293388/155413423-f255d0a9-ff19-485c-ae33-63cd0571ad00.png)

**Comment by jmanc3** [comment]
@Faithy3 do you have multiple screens? is xfwm4 doing some sort of dpi scaling?

**Comment by Faithy3** [comment]
I only have one screen, and scaling is set to 100% everywhere as far as I'm aware.

**Comment by jmanc3** [comment]
@Faithy3 try out [d963f60](https://github.com/jmanc3/winbar/commit/d963f600e1fd4baf4781e34ce8bf4c2ce10bd804) and see if it's fixed. Let me know

**Comment by Faithy3** [comment]
Scaling issue is fixed now, thanks!
