### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Tomas-M** [jmanc3/winbar#55]
This project is simply awesome! :)

I compiled winbar on Debian.
First thing, it is missing several packages, I installed all as specified for ubuntu, and Debian needs these extra:
libcurl4 libcurl4-openssl-dev libxcb-xinput-dev libxcb-xinput0

Now, when I use compiled winbar binary, I get segmentation fault in most cases.
But when I use 'strace winbar' to see what system calls are happening, it seems to work mostly. Strange.

In all cases, sometimes I get some errors before segfault. For example

Glib-GObject-WARNING **: 20:02:14.874: class of invalid type '(null)'

or

Pango-CRITICAL **: 19:59:50.995: pango_shape_internal: assertion 'paragraph_text + paragraph_length >= item_text + item_length' failed

Hope you can do something about it :) Let me know please if I can provide any debug info. Just keep in mind I have no idea how to debug software so you may need to provide more detailed instructions.

Thanks!

**Comment by jmanc3** [comment]
Yeah this is a weird one that happens to me every so often, but since it's so rare, it was hard for me to debug. But if you say it happens frequently on Debian, I should be able to track it down. I'll take a look

**Comment by jmanc3** [comment]
@Tomas-M Wasn't able to reproduce on a VM.
- What desktop environment are you running (Plasma, Gnome, Xfce, etc...)? 
- What display server (X11 or Wayland)? 
- Do these segfaults happen sporadically or every-time?
- What sound server: (Pipewire, Also, Pulseaudio)?

**Comment by Tomas-M** [comment]
I am using Debian 12. However I am using it on my custom version of Debian, since I am a creator of Slax Linux (based on Debian and Slackware) and I am testing it on my version of Slax based on debian 12. WM is fluxbox and display server is x11. Since I am testing it in virtualbox, I can send you the exact ISO file I am booting from (no installation, liveCD).

Slax is stripped down Debian, but all main functionality should be there.

I am considering to add winbar to Slax as a default taskbar, if it works in a suitable way, but I wasn't able to test it much since it segfaults very often, almost always. What is strange is that when 'strace winbar' is used, it does not segfault so often, I have no explanation for that.

Here is download link for 64bit ISO:
https://slax.org/projects/temp/slax-64bit-12.1.0.iso

Simply boot it, and use apt install to install the necessary development tools to compile. Make sure you select 4GB RAM or even more in virtual machine, since all installed stuff is saved in memory because there is no disk needed.

Hope it helps

**Comment by jmanc3** [comment]
@Tomas-M should be fixed since 2b82bc2494243c2f0a3714b4c5533974f84e0777, but DO let me know.

Side Note: I was reading up on slax, and while I do believe that winbar is far-and-away the best 'taskbar,'  it might not be the best fit for slax given how focused slax is on being lightweight. On my machine winbar takes up 150mb of ram by itself.

**Comment by Tomas-M** [comment]
I can confirm it does no longer segfault, the problem seems to be fixed. Great job! :)
Slax is not so lightweight as people think :) winbar seems to take similar amount of memory such as xfce4-panel, which seems fine for me. I will give it a try and I will see, so far it looks very good :)
