### ISSUE TITLE
Bug: selecting window when grouped

### ISSUE THREAD

**Issue by Tomas-M** [jmanc3/winbar#56]
When I open, for instance, three xterm windows, Winbar consolidates them into a single icon. Hovering over this icon in Winbar triggers a tooltip preview of the three xterm windows, and I can select the one I wish to focus on by clicking on it.

However, I occasionally encounter an issue where clicking (or tapping on the touchpad) doesn't yield any response, as if I hadn't clicked at all. Interestingly, if I move the mouse pointer even slightly — just by one pixel — the previously clicked window comes into focus and the tooltip previews disappear, exactly as they would have if the initial click was successful.

This behavior looks like a bug.

**Comment by Tomas-M** [comment]
I will add that I am using fluxbox WM and X11

**Comment by jmanc3** [comment]
@Tomas-M if you have the time to check, I think this should be fixed on the latest commit. I tested it myself and it never saw it occur again, but I could've just got lucky.
