### ISSUE TITLE
Can't find a way to change the clock to look more like Windows

### ISSUE THREAD

**Issue by MacroHard-Winux** [jmanc3/winbar#57]
I want it to remove the text and only show the numbers, but can't find option in the config file
![image](https://github.com/jmanc3/winbar/assets/129944538/6f8d7730-afc7-4fa6-a8d6-da66d3d1cbf6)

**Comment by jmanc3** [comment]
Change the string on the following following line:
https://github.com/jmanc3/winbar/blob/e95e01e5f70df1a22cdeae9464a0a02486112b81/src/taskbar.cpp#L998
to:
"%I:%M %p"

and change the string in the following line:
https://github.com/jmanc3/winbar/blob/e95e01e5f70df1a22cdeae9464a0a02486112b81/src/taskbar.cpp#L1006
to:
"%m"

**Comment by jmanc3** [comment]
As of [e5b8e52](https://github.com/jmanc3/winbar/commit/e5b8e521821c94a73a4354155704bdb7c017427a), you can simply set the date style to 'Windows 10' in the settings menu, instead of having to modify the source code.

**Comment by MacroHard-Winux** [comment]
Nice thx
