### ISSUE TITLE
Segmentation fault upon opening start menu

### ISSUE THREAD

**Issue by seba4316** [jmanc3/winbar#60]
Opening the start menu, being by clicking on the Windows logo or using the Meta key, consistently triggers a segfault after commit c1c4160
Here's the core dump:
```
Core was generated by `./winbar'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  start_app_menu () at .../winbar/src/app_menu.cpp:1792
1792	        if (settings.x + settings.w > taskbar->screen_information->width_in_pixels) {
[Current thread is 1 (Thread 0x7fe2ae030e00 (LWP 26206))]
```

I'm running an Ubuntu 22.04 based distro on the Linux Kernel 6.2.0-34
My desktop environment is Openbox, resolution 1440x900

**Comment by jmanc3** [comment]
Fixed in latest commit

**Comment by seba4316** [comment]
Yes, was just looking into it and found screen_information to still be nullptr, can also confirm that fd84277 fixed it
