### ISSUE TITLE
Is there a way to validate if winbar is successfully installed

### ISSUE THREAD

**Issue by alejandrohagan** [jmanc3/winbar#61]
Thank you so much for the instructions! They are very thorough and well written.

I believe I successfully installed winbar -- however is there a way to validate? one of the my nvim plugins uses winbar as a dependency so even though I think it is successfully installed when I install that plugin it will pull the same winbar error

The below is the message I receive when I nstall the winbar install.sh file. 

```
Continuing...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hagan/winbar/newbuild
Consolidate compiler generated dependencies of target winbar
[100%] Built target winbar
Trying to install to /usr/local/bin/winbar
[100%] Built target winbar
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/bin/winbar
```

**Comment by jmanc3** [comment]
This project is for a taskbar on the desktop. I believe you're talking about the neovim plugin 'winbar' which is different. It seems like all you need is the latest version of nvim to get it, although I'm not sure.
Maybe there's more information at https://github.com/neovim/neovim
