### ISSUE TITLE
Can't disable search

### ISSUE THREAD

**Issue by mattatobin** [jmanc3/winbar#63]
Even when I disable the search bar it comes back up and steals focus every time I use the start button. Additionally, I expect when I click a second time for the menu to close. 

Basically, I want to disable search completely.

**Comment by jmanc3** [comment]
You should be able to configure the behavior in the settings as of: https://github.com/jmanc3/winbar/commit/b7b3691508111e21cc009e1d6fdf906f8e4276f8

As for the click: What window manager or display manager are you using?

**Comment by mattatobin** [comment]
I was testing under openbox. Also, had picom running if that could make a difference.
