### ISSUE TITLE
Icons "bounce" when switching workspaces

### ISSUE THREAD

**Issue by mattatobin** [jmanc3/winbar#64]
When I switch workspaces the icons dehighlight of course but also bounce as they realign back to exactly where they were. It is very jarring.

Perhaps an option to hide icons that are not on that desktop?

**Comment by mattatobin** [comment]
This was under Openbox.

**Comment by mattatobin** [comment]
I have more data since I switched back to openbox full time. Yeah, the bounce is an effect of popping in and out of existence for task icons right? Well in openbox they bounce cause the relevant icons aren't being hidden based on the virtual desktop.

**Comment by jmanc3** [comment]
This was because there is an animation when windows are mapped/unmapped, but this behavior can be adjusted now: [c298405](https://github.com/jmanc3/winbar/commit/c298405f799fa0d763421ec38ed0c390f10e6f90)
