### ISSUE TITLE
Support setting a directory as the "Start Menu Folder"

### ISSUE THREAD

**Issue by mattatobin** [jmanc3/winbar#66]
It would be really nice if one could set the source for the start menu to an arbitrary tree of desktop files and sub-directories and have it represented as Windows does.

**Comment by jmanc3** [comment]
@mattatobin Added this to the settings page as of:
[514622c](https://github.com/jmanc3/winbar/commit/514622c5b2f81d9ec951049e8a06aec3393ff098)

**Comment by mattatobin** [comment]
Sorry for the silence been working on other things. I will give this a new build and thrash at it. For fun I will try and run it in the Common Desktop Environment as well just to see what happens. Keep on being inspiring!
