### ISSUE TITLE
Runbox

### ISSUE THREAD

**Issue by mattatobin** [jmanc3/winbar#67]
Call me old, but in Windows I do typically use a combo of auto-run, basic start menu, and the runbox to do all my program execution. On linux, an arbitrary runbox on an easily pressed Winkey+r would be amazing.

**Comment by jmanc3** [comment]
Added in: https://github.com/jmanc3/winbar/commit/fcca7175c2f22d9460b3a5cb8b2213487c344b84

**Comment by mattatobin** [comment]
Wow, I .. didn't really expect such a quick response to my kinda rushed drive-thru style issue creation. I am duly impressed. I am not much of a c/cpp coder but it is on my list to learn. Perhaps I should start.. here. In the meantime, I surely will test and report all the things related to the issues I opened up.

Keep being awesome while I look for all the ways to contribute back ;)
