### ISSUE TITLE
Grouped Icons but with labels.

### ISSUE THREAD

**Issue by mattatobin** [jmanc3/winbar#68]
I like superbar features like the dock functions but I still like labels. Ungrouped this would also overlap with #29

**Comment by jmanc3** [comment]
[6a8987d](https://github.com/jmanc3/winbar/commit/6a8987dbe8fc7f4a442bf5330d042ff9beebb168) Added labels

**Comment by mattatobin** [comment]
Verified exactly as requested, love this project.
