### ISSUE TITLE
Launching nemo crashes winbar

### ISSUE THREAD

**Issue by pushqrdx** [jmanc3/winbar#7]
This is a weird one but launching nemo (through terminal or through winbar) causes it to crash with a free on an invalid pointer, and relaunching winbar while nemo is open always crashes on startup with the same message
```
free(): invalid next size (fast)
```

**Comment by jmanc3** [comment]
Fixed in de76624.

**Comment by pushqrdx** [comment]
@jmanc3 hmm, not sure if it's fixed, i just fetched master and nemo still crashes winbar with the same message

**Comment by pushqrdx** [comment]
doesn't happen anymore with Paper icons after computer restart so gonna close this

**Comment by jmanc3** [comment]
@pushqrdx could it have been possible that linux was doing something funky and the winbar binary wasn't actually being updated, leading to running the same winbar version with the issue instead of the one that "fixed" it?

**Comment by pushqrdx** [comment]
@jmanc3 i mean winbar is a single binary and i was pretty sure that latest build was installed, i don't know why it was fixed after reboot, so far so good but i haven't rebooted since then but i killed winbar once because it was leaking memory and clock was frozen for some reason
