### ISSUE TITLE
Question about location of non-cfg resources.

### ISSUE THREAD

**Issue by mattatobin** [jmanc3/winbar#70]
I am going to write a spec file to build winbar with rpmbuild so is there a system location where resources in winbar.zip can live? Also, some sort of provision to copy an etc cfg to the user's directory upon start or change if not existent?

**Comment by jmanc3** [comment]
At the moment, the only place winbar checks for its resources is $HOME/.config/winbar.
It wouldn't be too hard to change it so that it checks /etc/winbar/* instead, and have the install script unzip into that folder.
Of course, since we can't write into that directory we'll still have to save and read transient files front ~/.config/winbar.
Would that work fro you?

**Comment by jmanc3** [comment]
@mattatobin Although I didn't write this install script, this is an install script for winbar on the AUR
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=winbar-git

I'm not familiar with rpmbuild but I would guess it's possible for it to do something similar as that script does, which does the unzip as a post step or something.

(On the wrapper script: how would it know where winbar.zip is?)

**Comment by mattatobin** [comment]
Well, the AUR package extracts the resources to a system share location and then as a post-install step copies it to the user profile. Basically it is a direct translation of the install script more or less.

I don't think RPM has a post-install task that can target a specific user or current user because the only user that can install packages is root when using dnf.

Also, how will the wrapper know where things are? There are a couple ways to deal with that. If it is spec file specific as in not apart of your project then I simply can generate the wrapper with populated locations. If it is part of your setup, then cmake can preprocess it and fill it with paths or some other means like reasonable guess based on the Filesystem Heirarchy Standard.

----

Aside: Openbox, Nemo (with Desktop), and winbar.

![Screenshot from 2024-05-28 17-18-24](https://github.com/jmanc3/winbar/assets/3889475/75b11fcf-4198-43ae-aabb-0f5317cae9d5)

**Comment by jmanc3** [comment]
@mattatobin Can rpmbuild unzip winbar.zip into /etc/winbar? That seems like the simplest solution if it can. It's what we should be doing anyways as a lot of what's in .config/winbar is not user specific anyways.

**Comment by mattatobin** [comment]
If you want to follow the FHS, only the initial configuration file should live in `etc` the resources should live in `usr/share/winbar` and the program should be handling copying read-only global configuration to the user's config. The build system should also be setup to obey `--prefix` when configuring and `DESTDIR=` for installing.

BUUUT that sure is a lot of requirements and the list of demands to be putting upon you all at once. So my solution is the startup wrapper that can serve if/until you decide to perform build system voodoo (and yes it is absolutely voodoo, I know from experience).

**Comment by mattatobin** [comment]
I have not forgotten about this I just kinda had an unexpected request for my specific skills on some other tasks that only I can accomplish (outside Mozilla).

**Comment by jmanc3** [comment]
I've been working on it but haven't pushed yet. The cmake script now unzip the winbar.zip and then installs the files where they are needed. I just need to copy them into the local ~/.config at boot.

**Comment by mattatobin** [comment]
I been researching the cmake version of it.

In standard `autohell` `--prefix` is the directory prefix of where the files will be installed while DESTDIR controls where the files are actually installed to which normally is the same as prefix or default except when you go to make packages. It's easier to dump these into an isolated folder for ease of packaging even though that isn't the location where they will live when installed. Otherwise one would have to track the files early on and capture and pick em out for packaging from their standard or final location.

Cmake though because it makes things easy it also makes complicated things harder to work out oddly enough.

**Comment by jmanc3** [comment]
@mattatobin [5948ed4](https://github.com/jmanc3/winbar/commit/5948ed41057a6b57d4f47971a5771bf1cf73cda4) CMake puts the resources into the 'global' resource locations '/etc', and '/usr/share/winbar', and then they are copied to the user on program boot.

If you need something done different, let me know

**Comment by mattatobin** [comment]
That sounds great i was having some slight issues with the script logic it works but error chcking for all the permitations like files already exists or dir is there cfg is there but not res files its a good handful of cases but since you beat me on script vs appcode I am more than happy.

You have a great project right at its start and I am am just privileged to be buzzing about poking at it.
