### ISSUE TITLE
Windows logo could get a downstream distributor sued by Microsoft.

### ISSUE THREAD

**Issue by mattatobin** [jmanc3/winbar#71]
Can the start button logo be changed to different ones? Because if I do a CentOS remix or LFS distro and package and distribute this with a Windows Logo that is kinda not gonna work out too well.

As well as issues for yourself. Microsoft has a long history of going after stuff like this. Not that they have nearly the power to force you to redesign the program UI they may have had in the 90s but a logo? I wouldn't bet against it. Also, they kinda own Github too lol.

**Comment by jmanc3** [comment]
Changed the default icon to a neutral one, and added setting to use old one (swappable: ~/.config/winbar/resources/applications.png). [fc37768](https://github.com/jmanc3/winbar/commit/fc377682f2d460c8b0f7cc0b69e009a5b0a6be83)

**Comment by mattatobin** [comment]
Ah nice. Thank you so much for everything you have done on this again. It has to re-inspire me to do actual things. :)
