### ISSUE TITLE
Error while compiling on Debian 12

### ISSUE THREAD

**Issue by wodo42** [jmanc3/winbar#73]
Trying to compile on Debian 12 throws the Error "/home/user/winbar/src/taskbar.cpp: In function 'int size_icons(AppClient*, cairo_t*, Container*)':
/home/user/winbar/src/taskbar.cpp:1233:9: error: expected primary-expression before '}' token"

Here's a screenshot of the output:
https://1drv.ms/i/c/07de4a63c369ed59/ES3SzBbuc6NEvOsQhCYSCY0Bz_dLpieSqCfoTPg-d-WMiw

**Comment by jmanc3** [comment]
Should be fixed in: [b475064](https://github.com/jmanc3/winbar/commit/b475064d1861768f2e961a07dc360ab7862d7f93)
