### ISSUE TITLE
Trouble compiling on debian

### ISSUE THREAD

**Issue by PinkyPis** [jmanc3/winbar#74]
Hello, I tried compiling on debian testing but got this, how should I go about this?
`./install.sh
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/labjo/winbar/newbuild
Building CXX object CMakeFiles/winbar.dir/src/action_center_menu.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/config.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/main.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/globals.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/app_menu.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/notifications.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/bluetooth_menu.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/date_menu.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/pinned_icon_right_click.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/chatgpt.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/battery_menu.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/components.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/pinned_icon_editor.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/root.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/plugins_menu.cpp.o
Building CXX object CMakeFiles/winbar.dir/src/search_menu.cpp.o
/home/labjo/winbar/src/globals.cpp:7:26: fatal error: opening dependency file CMakeFiles/winbar.dir/src/globals.cpp.o.d: Permission denied
    7 | globals *global = nullptr;
      |                          ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:188: CMakeFiles/winbar.dir/src/globals.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/labjo/winbar/src/pinned_icon_editor.cpp: In function ‘void tab_key_event(AppClient*, cairo_t*, Container*, bool, xkb_keysym_t, char*, uint16_t, xkb_key_direction)’:
/home/labjo/winbar/src/pinned_icon_editor.cpp:377:36: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  377 |                                    "icon_name_key_event");
      |                                    ^~~~~~~~~~~~~~~~~~~~~
/home/labjo/winbar/src/pinned_icon_editor.cpp:380:36: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  380 |                                    "icon_name_key_event");
      |                                    ^~~~~~~~~~~~~~~~~~~~~
/home/labjo/winbar/src/pinned_icon_editor.cpp:383:36: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  383 |                                    "icon_name_key_event");
      |                                    ^~~~~~~~~~~~~~~~~~~~~
/home/labjo/winbar/src/root.cpp:257:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/root.cpp.o.d: Permission denied
  257 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:272: CMakeFiles/winbar.dir/src/root.cpp.o] Error 1
/home/labjo/winbar/src/pinned_icon_editor.cpp: At global scope:
/home/labjo/winbar/src/pinned_icon_editor.cpp:585:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/pinned_icon_editor.cpp.o.d: Permission denied
  585 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:230: CMakeFiles/winbar.dir/src/pinned_icon_editor.cpp.o] Error 1
/home/labjo/winbar/src/action_center_menu.cpp:507:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/action_center_menu.cpp.o.d: Permission denied
  507 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:76: CMakeFiles/winbar.dir/src/action_center_menu.cpp.o] Error 1
/home/labjo/winbar/src/notifications.cpp:577:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/notifications.cpp.o.d: Permission denied
  577 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:216: CMakeFiles/winbar.dir/src/notifications.cpp.o] Error 1
/home/labjo/winbar/src/components.cpp:2842:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/components.cpp.o.d: Permission denied
 2842 | }
      | ^
compilation terminated.
/home/labjo/winbar/src/app_menu.cpp:1860:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/app_menu.cpp.o.d: Permission denied
 1860 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:146: CMakeFiles/winbar.dir/src/components.cpp.o] Error 1
make[2]: *** [CMakeFiles/winbar.dir/build.make:90: CMakeFiles/winbar.dir/src/app_menu.cpp.o] Error 1
/home/labjo/winbar/src/pinned_icon_right_click.cpp:581:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/pinned_icon_right_click.cpp.o.d: Permission denied
  581 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:244: CMakeFiles/winbar.dir/src/pinned_icon_right_click.cpp.o] Error 1
/home/labjo/winbar/src/main.cpp:317:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/main.cpp.o.d: Permission denied
  317 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:202: CMakeFiles/winbar.dir/src/main.cpp.o] Error 1
/home/labjo/winbar/src/chatgpt.cpp:1107:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/chatgpt.cpp.o.d: Permission denied
 1107 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:132: CMakeFiles/winbar.dir/src/chatgpt.cpp.o] Error 1
/home/labjo/winbar/src/battery_menu.cpp:491:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/battery_menu.cpp.o.d: Permission denied
  491 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:104: CMakeFiles/winbar.dir/src/battery_menu.cpp.o] Error 1
/home/labjo/winbar/src/date_menu.cpp:1033:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/date_menu.cpp.o.d: Permission denied
 1033 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:174: CMakeFiles/winbar.dir/src/date_menu.cpp.o] Error 1
/home/labjo/winbar/src/search_menu.cpp:1791:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/search_menu.cpp.o.d: Permission denied
 1791 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:286: CMakeFiles/winbar.dir/src/search_menu.cpp.o] Error 1
/home/labjo/winbar/src/bluetooth_menu.cpp:1611:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/bluetooth_menu.cpp.o.d: Permission denied
 1611 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:118: CMakeFiles/winbar.dir/src/bluetooth_menu.cpp.o] Error 1
/home/labjo/winbar/src/config.cpp:412:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/config.cpp.o.d: Permission denied
  412 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:160: CMakeFiles/winbar.dir/src/config.cpp.o] Error 1
/home/labjo/winbar/src/plugins_menu.cpp:1053:1: fatal error: opening dependency file CMakeFiles/winbar.dir/src/plugins_menu.cpp.o.d: Permission denied
 1053 | }
      | ^
compilation terminated.
make[2]: *** [CMakeFiles/winbar.dir/build.make:258: CMakeFiles/winbar.dir/src/plugins_menu.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/winbar.dir/all] Error 2
make: *** [Makefile:136: all] Error 2`

**Comment by jmanc3** [comment]
Probably just need to run install script as sudo

**Comment by PinkyPis** [comment]
Thanks
