### ISSUE TITLE
Launching run prompt when the Super+R pressed twice causes segmentation fault

### ISSUE THREAD

**Issue by luutuyen2k9** [jmanc3/winbar#78]
https://github.com/user-attachments/assets/d9fc9cb1-4303-4b31-9223-58451b84dcf5

**Comment by jmanc3** [comment]
What should the expected behavior be? Should the run menu simply close so that the shortcut is like a toggle? Or should it just reset the state of the text field and keep the run menu open?

**Comment by luutuyen2k9** [comment]
The run prompt should be simply close before new run prompt was opened when Super + R was pressed again

> What should the expected behavior be? Should the run menu simply close so that the shortcut is like a toggle? Or should it just reset the state of the text field and keep the run menu open?

**Comment by jmanc3** [comment]
should no longer crash
