### ISSUE TITLE
the winbar.cfg file in the zip is probably broken

### ISSUE THREAD

**Issue by pushqrdx** [jmanc3/winbar#8]
i can't change anything with the config file, and i always get 

```
Parsing error:  /root/.config/winbar/winbar.cfg Line: 474
```

it works if i remove the themes section, so probably something in there drifted overtime

**Comment by jmanc3** [comment]
Most likely you're missing a comma at the end of one of your lines or braces. Unfortunately libconfig++ doesn't really export much more information than what you were given, but eventually we are going to have a settings app that'll read and write to the config without errors.

You should try finding the missing comma/brace and add it. Or you can copy and paste the one in winbar.zip, which shouldn't have errors, and try to get back to where you were.
